import bcrypt from "bcryptjs"; import crypto from "node:crypto"; import jwt, { type SignOptions } from "jsonwebtoken"; import { nanoid } from "nanoid"; import type { AuthSession, AuthUser, Role } from "@profilex/shared"; import { ACCESS_TOKEN_TTL, JWT_SECRET, REFRESH_TOKEN_TTL_DAYS } from "../config.js"; import type { AppDatabase } from "../database/db.js"; import { log } from "../logger.js";
type UserRow={id:string;name:string;email:string;password_hash:string;role:Role;created_at:string};
export async function registerUser(db:AppDatabase,input:{name?:string;email?:string;password?:string}){const name=String(input.name??"").trim(), email=norm(input.email), password=String(input.password??""); if(name.length<2)throw new Error("Name must contain at least 2 characters."); validEmail(email); validPassword(password); if(await db.one("SELECT id FROM users WHERE email=$1",[email]))throw new Error("Account with this email already exists."); const now=new Date().toISOString(), user:UserRow={id:nanoid(),name,email,password_hash:await bcrypt.hash(password,12),role:"client",created_at:now}; await db.exec("INSERT INTO users (id,name,email,password_hash,role,created_at) VALUES ($1,$2,$3,$4,$5,$6)",[user.id,user.name,user.email,user.password_hash,user.role,user.created_at]); log("auth","registered",{userId:user.id}); return createSession(db,user)}
export async function loginUser(db:AppDatabase,input:{email?:string;password?:string}){const user=await db.one<UserRow>("SELECT * FROM users WHERE email=$1",[norm(input.email)]); if(!user||!(await bcrypt.compare(String(input.password??""),user.password_hash)))throw new Error("Invalid email or password."); log("auth","login",{userId:user.id}); return createSession(db,user)}
export async function refreshSession(db:AppDatabase,refreshToken?:string){if(!refreshToken)throw new Error("Refresh token required."); const hash=hashToken(refreshToken); const row=await db.one<any>("SELECT rt.*,u.* FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=$1 AND rt.revoked_at IS NULL AND rt.expires_at>now()",[hash]); if(!row)throw new Error("Refresh token expired or invalid."); await db.exec("UPDATE refresh_tokens SET revoked_at=$1 WHERE id=$2",[new Date().toISOString(),row.id]); return createSession(db,row)}
export function getUserByToken(_db:AppDatabase,token?:string):AuthUser|undefined{if(!token)return undefined; try{const p=jwt.verify(token,JWT_SECRET) as AuthUser; return p?.id&&p?.email?p:undefined}catch{return undefined}}
export async function logoutUser(db:AppDatabase,refreshToken?:string){if(refreshToken)await db.exec("UPDATE refresh_tokens SET revoked_at=$1 WHERE token_hash=$2",[new Date().toISOString(),hashToken(refreshToken)]);}
async function createSession(db:AppDatabase,user:UserRow):Promise<AuthSession & {refreshToken:string}>{const publicUser=mapUser(user), refreshToken=crypto.randomBytes(48).toString("base64url"), now=new Date(), expires=new Date(now.getTime()+REFRESH_TOKEN_TTL_DAYS*86400000); await db.exec("INSERT INTO refresh_tokens (id,user_id,token_hash,expires_at,created_at) VALUES ($1,$2,$3,$4,$5)",[nanoid(),user.id,hashToken(refreshToken),expires.toISOString(),now.toISOString()]); return{token:jwt.sign(publicUser,JWT_SECRET,{expiresIn: ACCESS_TOKEN_TTL as SignOptions["expiresIn"]}),refreshToken,user:publicUser}}
function mapUser(u:Pick<UserRow,"id"|"name"|"email"|"role"|"created_at">):AuthUser{return{id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.created_at}} function norm(e?:string){return String(e??"").trim().toLowerCase()} function validEmail(e:string){if(!/^\S+@\S+\.\S+$/.test(e))throw new Error("Enter a valid email address.")} function validPassword(p:string){if(p.length<8)throw new Error("Password must contain at least 8 characters.")} function hashToken(t:string){return crypto.createHash("sha256").update(t).digest("hex")}
