import { spawn, spawnSync } from "node:child_process"; import { nanoid } from "nanoid"; import type { RdpConnection } from "@profilex/shared"; import type { AppDatabase } from "../database/db.js"; import { decryptSecret, encryptSecret } from "../security/encryption.js";
export async function listRdpConnections(db:AppDatabase){return (await db.query("SELECT * FROM rdp_connections ORDER BY name ASC")).map((row) => mapRdp(row))}
export async function createRdpConnection(db:AppDatabase,input:Partial<RdpConnection>){const now=new Date().toISOString(), c=normalizeInput(input,now); await db.exec(`INSERT INTO rdp_connections (id,name,host,username,password_encrypted,domain,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[c.id,c.name,c.host,c.username,encryptSecret(input.password),c.domain,now,now]); return c}
export async function updateRdpConnection(db:AppDatabase,id:string,patch:Partial<RdpConnection>){const current=await getRdpConnection(db,id,{includePassword:true}); if(!current)return undefined; const next=normalizeInput({...current,...patch},current.createdAt,id); await db.exec(`UPDATE rdp_connections SET name=$1,host=$2,username=$3,password_encrypted=$4,domain=$5,updated_at=$6 WHERE id=$7`,[next.name,next.host,next.username,patch.password===undefined?encryptSecret(current.password):encryptSecret(patch.password),next.domain,next.updatedAt,id]); return getRdpConnection(db,id)}
export async function deleteRdpConnection(db:AppDatabase,id:string){const current=await getRdpConnection(db,id); await db.exec("DELETE FROM rdp_connections WHERE id=$1",[id]); return Boolean(current)}
export async function getRdpConnection(db:AppDatabase,id:string,options?:{includePassword?:boolean}){const row=await db.one<any>("SELECT * FROM rdp_connections WHERE id=$1",[id]); return row?mapRdp(row,options):undefined}
export async function launchRdpConnection(db:AppDatabase,id:string){const c=await getRdpConnection(db,id,{includePassword:true}); if(!c)return undefined; if(process.platform!=="win32")throw new Error("RDP launch is supported only on Windows."); const target=!c.domain||c.username.includes("\\")||c.username.includes("@")?c.username:`${c.domain}\\${c.username}`; if(c.password){spawnSync("cmdkey.exe",["/delete:TERMSRV/"+c.host],{windowsHide:true,stdio:"ignore"}); spawnSync("cmdkey.exe",["/generic:TERMSRV/"+c.host,"/user:"+target,"/pass:"+c.password],{windowsHide:true,stdio:"ignore"});} spawn("mstsc.exe",["/v:"+c.host],{detached:true,windowsHide:false,stdio:"ignore"}).unref(); const now=new Date().toISOString(); await db.exec("UPDATE rdp_connections SET last_launched_at=$1,updated_at=$1 WHERE id=$2",[now,id]); return getRdpConnection(db,id)}
function normalizeInput(input:Partial<RdpConnection>,createdAt=new Date().toISOString(),id=nanoid()):RdpConnection{const name=String(input.name??"").trim(),host=String(input.host??"").trim(),username=String(input.username??"").trim(),domain=String(input.domain??"").trim()||undefined; if(!name)throw new Error("RDP name is required."); if(!host)throw new Error("RDP host / IP is required."); if(!username)throw new Error("RDP login is required."); return{id,name,host,username,domain,createdAt,updatedAt:new Date().toISOString()}}
function mapRdp(row:any,options?:{includePassword?:boolean}):RdpConnection{const password=decryptSecret(row.password_encrypted); return{id:row.id,name:row.name,host:row.host,username:row.username,...(options?.includePassword?{password}:{}),hasPassword:Boolean(password),domain:row.domain??undefined,createdAt:row.created_at,updatedAt:row.updated_at,lastLaunchedAt:row.last_launched_at??undefined}}
