import type { CloudAppLockSettings, ProxylineSettings, SmtpSettings } from "@profilex/shared";
import type { AppDatabase } from "../database/db.js";
import { decryptSecret, encryptSecret } from "../security/encryption.js";
const SMTP_SETTINGS_KEY="smtp", PROXYLINE_SETTINGS_KEY="proxyline", APP_LOCK_SETTINGS_KEY="appLock";
const defaultSmtpSettings:SmtpSettings={enabled:false,host:"",port:587,secure:false,startTls:true,fromEmail:"workspace@company.local",fromName:"ProfileX",inviteBaseUrl:"profilex://invite"};
function readValue(value:any){return typeof value==='string'?JSON.parse(value):value}
export async function getSmtpSettings(db:AppDatabase, options:{includePassword?:boolean}={}){const row=await db.one<any>("SELECT value FROM settings WHERE key=$1",[SMTP_SETTINGS_KEY]); if(!row)return defaultSmtpSettings; const parsed=readValue(row.value); const settings:any={...defaultSmtpSettings,...parsed,password:options.includePassword?decryptSecret(parsed.passwordEncrypted):undefined,hasPassword:Boolean(parsed.passwordEncrypted)}; delete settings.passwordEncrypted; return settings as SmtpSettings;}
export async function updateSmtpSettings(db:AppDatabase, patch:Partial<SmtpSettings>){const current=await getRawSmtpSettings(db); const trimmedPassword=typeof patch.password==='string'?patch.password.trim():undefined; const next={...current,enabled:patch.enabled??current.enabled,host:patch.host?.trim()??current.host,port:Number.isFinite(patch.port)?patch.port:current.port,secure:patch.secure??current.secure,startTls:patch.startTls??current.startTls,username:patch.username?.trim()||undefined,fromEmail:patch.fromEmail?.trim()||current.fromEmail,fromName:patch.fromName?.trim()||current.fromName,inviteBaseUrl:patch.inviteBaseUrl?.trim()||current.inviteBaseUrl,passwordEncrypted:trimmedPassword?encryptSecret(trimmedPassword):current.passwordEncrypted}; await db.exec("INSERT INTO settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value",[SMTP_SETTINGS_KEY,JSON.stringify(next)]); return getSmtpSettings(db);}
async function getRawSmtpSettings(db:AppDatabase){const row=await db.one<any>("SELECT value FROM settings WHERE key=$1",[SMTP_SETTINGS_KEY]); return row?{...defaultSmtpSettings,...readValue(row.value)}:{...defaultSmtpSettings,passwordEncrypted:undefined};}
export async function getProxylineSettings(db:AppDatabase, options:{includeApiKey?:boolean}={}){const row=await db.one<any>("SELECT value FROM settings WHERE key=$1",[PROXYLINE_SETTINGS_KEY]); if(!row)return {}; const parsed=readValue(row.value); const apiKey=parsed.apiKeyEncrypted?decryptSecret(parsed.apiKeyEncrypted):undefined; return {apiKey:options.includeApiKey?apiKey:undefined,hasApiKey:Boolean(apiKey),accountName:parsed.accountName,keySuffix:apiKey?apiKey.slice(-4):undefined};}
export async function updateProxylineSettings(db:AppDatabase, patch:Partial<ProxylineSettings>){const current=await getRawProxylineSettings(db); const next={...current,apiKeyEncrypted:patch.apiKey===undefined?current.apiKeyEncrypted:encryptSecret(patch.apiKey.trim()),accountName:patch.accountName?.trim()||current.accountName}; await db.exec("INSERT INTO settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value",[PROXYLINE_SETTINGS_KEY,JSON.stringify(next)]); return getProxylineSettings(db);}
async function getRawProxylineSettings(db:AppDatabase){const row=await db.one<any>("SELECT value FROM settings WHERE key=$1",[PROXYLINE_SETTINGS_KEY]); return row?readValue(row.value):{apiKeyEncrypted:undefined};}
export async function deleteProxylineSettings(db:AppDatabase){await db.exec("DELETE FROM settings WHERE key=$1",[PROXYLINE_SETTINGS_KEY]); return {} as ProxylineSettings;}
export async function getCloudAppLockSettings(db:AppDatabase):Promise<CloudAppLockSettings>{const row=await db.one<any>("SELECT value FROM settings WHERE key=$1",[APP_LOCK_SETTINGS_KEY]); const value=row?readValue(row.value):undefined; return {enabled:Boolean(value?.enabled),updatedAt:value?.updatedAt}}
export async function updateCloudAppLockSettings(db:AppDatabase, patch:Partial<CloudAppLockSettings>){const next={enabled:Boolean(patch.enabled),updatedAt:new Date().toISOString()}; await db.exec("INSERT INTO settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value",[APP_LOCK_SETTINGS_KEY,JSON.stringify(next)]); return next}