import type { Role, TeamGroup, TeamInvitation, TeamMember, TeamWorkspaceData } from "@profilex/shared";
import { nanoid } from "nanoid";
import type { AppDatabase } from "../database/db.js";
import { logActivity } from "./activityService.js";
import { getSmtpSettings } from "./settingsService.js";
const mapMember=(r:any):TeamMember=>({id:r.id,workspaceId:r.workspace_id,name:r.name,email:r.email,role:r.role,active:Boolean(r.active)});
const mapGroup=(r:any):TeamGroup=>({id:r.id,workspaceId:r.workspace_id,name:r.name,description:r.description??undefined,createdAt:r.created_at});
const mapInvitation=(r:any,base="profilex://invite"):TeamInvitation=>({id:r.id,workspaceId:r.workspace_id,memberId:r.member_id,email:r.email,token:r.token,status:r.status,inviteUrl:`${base.replace(/\/$/,"")}/${r.token}`,invitedAt:r.invited_at});
export async function getTeamWorkspace(db:AppDatabase):Promise<TeamWorkspaceData>{const members=(await db.query("SELECT * FROM team_members ORDER BY role ASC,name ASC")).map(mapMember); const groupRows=await db.query("SELECT * FROM profile_groups ORDER BY name ASC"); const groups=[] as Array<TeamGroup & {memberIds:string[];profileIds:string[]}>; for(const row of groupRows){const g=mapGroup(row); groups.push({...g,memberIds:(await db.query<any>("SELECT member_id FROM team_group_members WHERE group_id=$1",[g.id])).map(x=>String(x.member_id)),profileIds:(await db.query<any>("SELECT id FROM profiles WHERE profile_group_id=$1 ORDER BY name ASC",[g.id])).map(x=>String(x.id))})} const smtp=await getSmtpSettings(db); const invitations=(await db.query("SELECT * FROM team_invitations ORDER BY invited_at DESC")).map(r=>mapInvitation(r,smtp.inviteBaseUrl)); return{members,groups,invitations}}
export async function createTeamMember(db:AppDatabase,input:{name:string;email:string;role:Role;groupIds?:string[]}){const member:TeamMember={id:nanoid(),workspaceId:"workspace-default",name:input.name.trim(),email:input.email.trim(),role:input.role,active:false}; if(!member.name||!member.email)throw new Error("Member name and email are required"); await db.exec("INSERT INTO team_members (id,workspace_id,name,email,role,active) VALUES ($1,$2,$3,$4,$5,$6)",[member.id,member.workspaceId,member.name,member.email,member.role,false]); await setMemberGroups(db,member.id,input.groupIds??[]); const invitation=await createInvitation(db,member.id,member.email); await logActivity(db,"member.invited",`${member.name} <${member.email}>`); return{...member,inviteUrl:invitation.inviteUrl}}
export async function resendTeamInvitation(db:AppDatabase,memberId:string){const member=await db.one<any>("SELECT * FROM team_members WHERE id=$1",[memberId]); if(!member)return undefined; await db.exec("UPDATE team_invitations SET status='revoked' WHERE member_id=$1 AND status='pending'",[memberId]); const inv=await createInvitation(db,memberId,member.email); await logActivity(db,"member.invite_resent",member.email); return inv}
export async function acceptTeamInvitation(db:AppDatabase,token:string){const inv=await db.one<any>("SELECT * FROM team_invitations WHERE token=$1 AND status='pending'",[token]); if(!inv)return undefined; await db.exec("UPDATE team_invitations SET status='accepted' WHERE id=$1",[inv.id]); await db.exec("UPDATE team_members SET active=true WHERE id=$1",[inv.member_id]); const smtp=await getSmtpSettings(db); return mapInvitation({...inv,status:"accepted"},smtp.inviteBaseUrl)}
async function createInvitation(db:AppDatabase,memberId:string,email:string){const smtp=await getSmtpSettings(db); const inv={id:nanoid(),workspaceId:"workspace-default",memberId,email,token:nanoid(32),status:"pending" as const,invitedAt:new Date().toISOString(),inviteUrl:""}; inv.inviteUrl=`${smtp.inviteBaseUrl.replace(/\/$/,"")}/${inv.token}`; await db.exec("INSERT INTO team_invitations (id,workspace_id,member_id,email,token,status,invited_at) VALUES ($1,$2,$3,$4,$5,$6,$7)",[inv.id,inv.workspaceId,inv.memberId,inv.email,inv.token,inv.status,inv.invitedAt]); return inv}
export async function updateTeamMember(db:AppDatabase,id:string,patch:Partial<TeamMember>&{groupIds?:string[]}){const row=await db.one<any>("SELECT * FROM team_members WHERE id=$1",[id]); if(!row)return undefined; const next={...mapMember(row),...patch}; await db.exec("UPDATE team_members SET name=$1,email=$2,role=$3,active=$4 WHERE id=$5",[next.name,next.email,next.role,next.active,id]); if(patch.groupIds)await setMemberGroups(db,id,patch.groupIds); return next}
export async function deleteTeamMember(db:AppDatabase,id:string){const row=await db.one<any>("SELECT * FROM team_members WHERE id=$1",[id]); await db.exec("DELETE FROM team_group_members WHERE member_id=$1",[id]); await db.exec("DELETE FROM team_members WHERE id=$1",[id]); return Boolean(row)}
export async function createTeamGroup(db:AppDatabase,input:{name:string;description?:string}){const g={id:nanoid(),workspaceId:"workspace-default",name:input.name.trim(),description:input.description?.trim()||undefined,createdAt:new Date().toISOString()}; if(!g.name)throw new Error("Group name is required"); await db.exec("INSERT INTO profile_groups (id,workspace_id,name,description,created_at) VALUES ($1,$2,$3,$4,$5)",[g.id,g.workspaceId,g.name,g.description,g.createdAt]); return g}
export async function updateTeamGroup(db:AppDatabase,id:string,patch:Partial<TeamGroup>){const row=await db.one<any>("SELECT * FROM profile_groups WHERE id=$1",[id]); if(!row)return undefined; const next={...mapGroup(row),...patch,name:patch.name?.trim()||row.name,description:patch.description?.trim()||undefined}; await db.exec("UPDATE profile_groups SET name=$1,description=$2 WHERE id=$3",[next.name,next.description,id]); return next}
export async function deleteTeamGroup(db:AppDatabase,id:string){if(!(await db.one("SELECT id FROM profile_groups WHERE id=$1",[id])))return false; const fallback=await ensureDefaultGroup(db); await db.exec("UPDATE profiles SET profile_group_id=$1 WHERE profile_group_id=$2",[fallback.id,id]); await db.exec("DELETE FROM profile_groups WHERE id=$1",[id]); return true}
export async function assignProfileGroup(db:AppDatabase,profileId:string,groupId:string){if(!(await db.one("SELECT id FROM profile_groups WHERE id=$1",[groupId]))||!(await db.one("SELECT id FROM profiles WHERE id=$1",[profileId])))return undefined; await db.exec("UPDATE profiles SET profile_group_id=$1,updated_at=$2 WHERE id=$3",[groupId,new Date().toISOString(),profileId]); return{profileId,groupId}}
export async function removeMemberFromGroup(db:AppDatabase,memberId:string,groupId:string){if(!(await db.one("SELECT id FROM profile_groups WHERE id=$1",[groupId]))||!(await db.one("SELECT id FROM team_members WHERE id=$1",[memberId])))return undefined; await db.exec("DELETE FROM team_group_members WHERE group_id=$1 AND member_id=$2",[groupId,memberId]); return{memberId,groupId}}
export async function removeProfileFromGroup(db:AppDatabase,profileId:string,groupId:string){if(!(await db.one("SELECT id FROM profile_groups WHERE id=$1",[groupId]))||!(await db.one("SELECT id FROM profiles WHERE id=$1",[profileId])))return undefined; const fallback=await ensureDefaultGroup(db); await db.exec("UPDATE profiles SET profile_group_id=$1,updated_at=$2 WHERE id=$3 AND profile_group_id=$4",[fallback.id,new Date().toISOString(),profileId,groupId]); return{profileId,groupId}}
async function setMemberGroups(db:AppDatabase,memberId:string,groupIds:string[]){await db.exec("DELETE FROM team_group_members WHERE member_id=$1",[memberId]); for(const id of groupIds.filter(Boolean))await db.exec("INSERT INTO team_group_members (group_id,member_id) VALUES ($1,$2) ON CONFLICT DO NOTHING",[id,memberId])}
async function ensureDefaultGroup(db:AppDatabase){const existing=await db.one<any>("SELECT * FROM profile_groups WHERE name='Default'"); if(existing)return existing; const row={id:nanoid(),workspace_id:"workspace-default",name:"Default",description:"Default profile access group",created_at:new Date().toISOString()}; await db.exec("INSERT INTO profile_groups (id,workspace_id,name,description,created_at) VALUES ($1,$2,$3,$4,$5)",[row.id,row.workspace_id,row.name,row.description,row.created_at]); return row}
