import { generateAuthenticationOptions, generateRegistrationOptions, verifyAuthenticationResponse, verifyRegistrationResponse } from "@simplewebauthn/server";
import type { AuthenticationResponseJSON, RegistrationResponseJSON } from "@simplewebauthn/server";
import type { AuthUser, PasskeyCredentialSummary } from "@profilex/shared";
import { nanoid } from "nanoid";
import { WEBAUTHN_ALLOWED_ORIGINS } from "../config.js";
import type { AppDatabase } from "../database/db.js";
import { createSessionForUserId } from "./authService.js";

const rpName = "ProfileX";
const challengeTtlMinutes = 10;
type CredentialRow = { user_id:string; credential_id:string; public_key:Buffer; counter:string|number; transports:string[]; created_at:string; last_used_at?:string };

export function resolveWebAuthnContext(originHeader?: string) {
  const origin = String(originHeader ?? "").replace(/\/$/, "");
  if (!WEBAUTHN_ALLOWED_ORIGINS.includes(origin)) throw new Error("WebAuthn origin is not allowed.");
  const hostname = new URL(origin).hostname;
  if (hostname === "127.0.0.1") throw new Error("Use http://localhost:5173 for local passkeys. 127.0.0.1 is not a valid WebAuthn RP ID.");
  return { origin, rpID: hostname };
}
export async function listPasskeys(db:AppDatabase,userId:string):Promise<PasskeyCredentialSummary[]>{return (await db.query<CredentialRow>('SELECT * FROM webauthn_credentials WHERE user_id=$1 ORDER BY created_at',[userId])).map(mapCredential)}
export async function removePasskey(db:AppDatabase,userId:string,credentialId:string){await db.exec('DELETE FROM webauthn_credentials WHERE user_id=$1 AND credential_id=$2',[userId,credentialId]); return {deleted:true}}
export async function beginRegistration(db:AppDatabase,user:AuthUser,originHeader?:string){const {origin,rpID}=resolveWebAuthnContext(originHeader); const credentials=await db.query<CredentialRow>('SELECT * FROM webauthn_credentials WHERE user_id=$1',[user.id]); const options=await generateRegistrationOptions({rpName,rpID,userID:new TextEncoder().encode(user.id),userName:user.email,userDisplayName:user.name,attestationType:'none',excludeCredentials:credentials.map((row)=>({id:row.credential_id,transports:row.transports as any})),authenticatorSelection:{residentKey:'required',userVerification:'preferred'}}); await saveChallenge(db,`register:${user.id}`,options.challenge,rpID,origin); return options}
export async function verifyRegistration(db:AppDatabase,user:AuthUser,response:RegistrationResponseJSON,originHeader?:string){const ctx=resolveWebAuthnContext(originHeader); const challenge=await takeChallenge(db,`register:${user.id}`,ctx); const verification=await verifyRegistrationResponse({response,expectedChallenge:challenge,expectedOrigin:ctx.origin,expectedRPID:ctx.rpID}); if(!verification.verified||!verification.registrationInfo) throw new Error('Passkey verification failed.'); const credential=verification.registrationInfo.credential; if(await db.one('SELECT 1 FROM webauthn_credentials WHERE credential_id=$1',[credential.id])) throw new Error('Credential already registered.'); await db.exec('INSERT INTO webauthn_credentials (user_id,credential_id,public_key,counter,transports,created_at) VALUES ($1,$2,$3,$4,$5,$6)',[user.id,credential.id,Buffer.from(credential.publicKey),credential.counter,credential.transports??[],new Date().toISOString()]); return {verified:true,credential:mapCredential({user_id:user.id,credential_id:credential.id,public_key:Buffer.from(credential.publicKey),counter:credential.counter,transports:(credential.transports??[]) as string[],created_at:new Date().toISOString()})}}
export async function beginLogin(db:AppDatabase,email:string,originHeader?:string){const normalized=email.trim().toLowerCase(); const {origin,rpID}=resolveWebAuthnContext(originHeader); const user=await db.one<any>('SELECT id FROM users WHERE email=$1',[normalized]); if(!user) throw new Error('No passkey found for this account.'); const credentials=await db.query<CredentialRow>('SELECT * FROM webauthn_credentials WHERE user_id=$1',[user.id]); if(!credentials.length) throw new Error('No passkey found for this account.'); const options=await generateAuthenticationOptions({rpID,userVerification:'preferred',allowCredentials:credentials.map((row)=>({id:row.credential_id,transports:row.transports as any}))}); await saveChallenge(db,`login:${normalized}`,options.challenge,rpID,origin); return options}
export async function beginDiscoverableLogin(db:AppDatabase,originHeader?:string){const {origin,rpID}=resolveWebAuthnContext(originHeader); const options=await generateAuthenticationOptions({rpID,userVerification:'preferred',allowCredentials:[]}); const challengeId=nanoid(); await saveChallenge(db,`discoverable:${challengeId}`,options.challenge,rpID,origin); return {challengeId,options}}
export async function verifyDiscoverableLogin(db:AppDatabase,challengeId:string,response:AuthenticationResponseJSON,originHeader?:string){const ctx=resolveWebAuthnContext(originHeader); const challenge=await takeChallenge(db,`discoverable:${challengeId}`,ctx); const row=await db.one<CredentialRow>('SELECT * FROM webauthn_credentials WHERE credential_id=$1',[response.id]); if(!row) throw new Error('Passkey not found.'); const verification=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:ctx.origin,expectedRPID:ctx.rpID,credential:{id:row.credential_id,publicKey:new Uint8Array(row.public_key),counter:Number(row.counter),transports:row.transports as any}}); if(!verification.verified) throw new Error('Passkey verification failed.'); await db.exec('UPDATE webauthn_credentials SET counter=$1,last_used_at=$2 WHERE credential_id=$3',[verification.authenticationInfo.newCounter,new Date().toISOString(),row.credential_id]); return createSessionForUserId(db,row.user_id)}export async function verifyLogin(db:AppDatabase,email:string,response:AuthenticationResponseJSON,originHeader?:string){const normalized=email.trim().toLowerCase(); const ctx=resolveWebAuthnContext(originHeader); const challenge=await takeChallenge(db,`login:${normalized}`,ctx); const row=await db.one<CredentialRow>('SELECT c.* FROM webauthn_credentials c JOIN users u ON u.id=c.user_id WHERE u.email=$1 AND c.credential_id=$2',[normalized,response.id]); if(!row) throw new Error('Passkey not found.'); const verification=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:ctx.origin,expectedRPID:ctx.rpID,credential:{id:row.credential_id,publicKey:new Uint8Array(row.public_key),counter:Number(row.counter),transports:row.transports as any}}); if(!verification.verified) throw new Error('Passkey verification failed.'); await db.exec('UPDATE webauthn_credentials SET counter=$1,last_used_at=$2 WHERE credential_id=$3',[verification.authenticationInfo.newCounter,new Date().toISOString(),row.credential_id]); return createSessionForUserId(db,row.user_id)}
export async function verifyUnlock(db:AppDatabase,user:AuthUser,response:AuthenticationResponseJSON,originHeader?:string){const ctx=resolveWebAuthnContext(originHeader); const challenge=await takeChallenge(db,`unlock:${user.id}`,ctx); const row=await db.one<CredentialRow>('SELECT * FROM webauthn_credentials WHERE user_id=$1 AND credential_id=$2',[user.id,response.id]); if(!row) throw new Error('Passkey not found.'); const verification=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:ctx.origin,expectedRPID:ctx.rpID,credential:{id:row.credential_id,publicKey:new Uint8Array(row.public_key),counter:Number(row.counter),transports:row.transports as any}}); if(!verification.verified) throw new Error('Passkey verification failed.'); await db.exec('UPDATE webauthn_credentials SET counter=$1,last_used_at=$2 WHERE credential_id=$3',[verification.authenticationInfo.newCounter,new Date().toISOString(),row.credential_id]); return {verified:true}}
export async function beginUnlock(db:AppDatabase,user:AuthUser,originHeader?:string){const {origin,rpID}=resolveWebAuthnContext(originHeader); const credentials=await db.query<CredentialRow>('SELECT * FROM webauthn_credentials WHERE user_id=$1',[user.id]); if(!credentials.length) throw new Error('No passkey configured.'); const options=await generateAuthenticationOptions({rpID,userVerification:'preferred',allowCredentials:credentials.map((row)=>({id:row.credential_id,transports:row.transports as any}))}); await saveChallenge(db,`unlock:${user.id}`,options.challenge,rpID,origin); return options}
async function saveChallenge(db:AppDatabase,key:string,challenge:string,rpID:string,origin:string){await db.exec('INSERT INTO webauthn_challenges (key,challenge,rp_id,origin,created_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (key) DO UPDATE SET challenge=EXCLUDED.challenge,rp_id=EXCLUDED.rp_id,origin=EXCLUDED.origin,created_at=EXCLUDED.created_at',[key,challenge,rpID,origin,new Date().toISOString()])}
async function takeChallenge(db:AppDatabase,key:string,ctx:{origin:string;rpID:string}){const row=await db.one<any>('DELETE FROM webauthn_challenges WHERE key=$1 RETURNING *',[key]); if(!row) throw new Error('Passkey challenge expired.'); if(row.origin!==ctx.origin||row.rp_id!==ctx.rpID) throw new Error('Passkey origin mismatch.'); if(Date.now()-new Date(row.created_at).getTime()>challengeTtlMinutes*60000) throw new Error('Passkey challenge expired.'); return row.challenge}
function mapCredential(row:CredentialRow):PasskeyCredentialSummary{return{credentialId:row.credential_id,transports:row.transports??[],createdAt:row.created_at,lastUsedAt:row.last_used_at}}
